### ISSUE TITLE
Idee to add commands to enable/disable MotionDetection

### ISSUE THREAD

**Issue by SA7BNT** [tropicoo/camerabot#2]
Hey Taras,

i just played a little bit with the Hikvision Cam today. 
How about to add enable/disable MotionDetection via command in Telegram.

> curl http://admin:passwd@IP_cam/MotionDetection/1 >motionetection_off.xml

Will give you the xml. Just enable it in xml, save and send it back.
So i´m thinking about if there are two xml on/off and Telegram just send it via curl then you have a new funktion.

> curl -T motionetection_on.xml http://admin:passwd@IP_cam/MotionDetection/1

> curl -T motionetection_off.xml http://admin:passwd@IP_cam/MotionDetection/1

How do you think about this and maybe a alarm push picture?

Best
Tim

**Comment by tropicoo** [comment]
Hi,

I've updated the bot with such possibility. Please test.
Configuration file template (structure) also changed a bit, needs to be updated on your side.
For alarm push picture - need to investigate.

Br,
Taras

**Comment by SA7BNT** [comment]
God morning Taras,

Great work, 👍
For the alarm push picture i will read a little bit more and see where it can be located.
Woundering if it is possible to get a signal from e-mail push funktion for Telegram  alarm push picture.
If i find something usefull i will let you know.

Thanks for add my idea 

Best
Tim
